services:
  # --- Service Backend (Python) ---
  api:
    image: alexzephyr/task-manager-back
    container_name: task-manager-back
    ports:
      - "8000:8000"
    restart: always

  # --- Service Frontend (Nginx) ---
  web:
    image: alexzephyr/task-manager-front
    container_name: task-manager-front
    ports:
      - "8080:80"
    restart: always
    depends_on:
      - api
