name: CI Compl√®te

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call-lint:
    uses: .github/workflows/01-lint.yml@master

  call-security:
    needs: call-lint
    uses: .github/workflows/02-snyk.yml@master
    secrets: inherit

  call-sonarqube:
    needs: call-security
    uses: .github/workflows/03-sonarqube.yml@master
    secrets: inherit

  call-docker:
    needs: call-sonarqube
    uses: .github/workflows/04-docker.yml@master

  notification:
    needs: call-docker
    uses: .github/workflows/05-completed.yml@master
