name: CI Compl√®te

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  call-lint:
    uses: ./.github/workflows/01-lint.yml

  call-snyk:
    uses: ./.github/workflows/02-snyk.yml
    secrets: inherit

  call-sonarqube:
    uses: ./.github/workflows/03-sonarqube.yml
    secrets: inherit
    permissions:
      contents: read
      pull-requests: read

  call-docker:
    needs: [call-lint, call-snyk, call-sonarqube]
    uses: ./.github/workflows/04-docker.yml

  notification:
    needs: call-docker
    uses: ./.github/workflows/05-completed.yml
